# Anchor name string constants.
# Coordinate convention: X+ = RIGHT, Y+ = FRONT, Z+ = TOP.

CENTER = "CENTER"
TOP    = "TOP"
BOTTOM = "BOTTOM"
FRONT  = "FRONT"
BACK   = "BACK"
LEFT   = "LEFT"
RIGHT  = "RIGHT"

# Box corners (8)
TOP_FRONT_LEFT    = "TOP_FRONT_LEFT"
TOP_FRONT_RIGHT   = "TOP_FRONT_RIGHT"
TOP_BACK_LEFT     = "TOP_BACK_LEFT"
TOP_BACK_RIGHT    = "TOP_BACK_RIGHT"
BOTTOM_FRONT_LEFT  = "BOTTOM_FRONT_LEFT"
BOTTOM_FRONT_RIGHT = "BOTTOM_FRONT_RIGHT"
BOTTOM_BACK_LEFT   = "BOTTOM_BACK_LEFT"
BOTTOM_BACK_RIGHT  = "BOTTOM_BACK_RIGHT"

# Box edge midpoints (12)
TOP_FRONT_EDGE    = "TOP_FRONT_EDGE"
TOP_BACK_EDGE     = "TOP_BACK_EDGE"
TOP_LEFT_EDGE     = "TOP_LEFT_EDGE"
TOP_RIGHT_EDGE    = "TOP_RIGHT_EDGE"
BOTTOM_FRONT_EDGE  = "BOTTOM_FRONT_EDGE"
BOTTOM_BACK_EDGE   = "BOTTOM_BACK_EDGE"
BOTTOM_LEFT_EDGE   = "BOTTOM_LEFT_EDGE"
BOTTOM_RIGHT_EDGE  = "BOTTOM_RIGHT_EDGE"
FRONT_LEFT_EDGE    = "FRONT_LEFT_EDGE"
FRONT_RIGHT_EDGE   = "FRONT_RIGHT_EDGE"
BACK_LEFT_EDGE     = "BACK_LEFT_EDGE"
BACK_RIGHT_EDGE    = "BACK_RIGHT_EDGE"

# Cylinder / disk rims
TOP_RIM    = "TOP_RIM"
BOTTOM_RIM = "BOTTOM_RIM"

STANDARD_ANCHORS = (CENTER, TOP, BOTTOM, FRONT, BACK, LEFT, RIGHT)
